language: R
sudo: required
cache: packages

r_packages:
  - bookdown

before_script:
  - chmod +x ./_build.sh

before_install:                           # Install Ruby and html-proofer
  #- sudo apt-get update && sudo apt-get --reinstall install -qq texlive-lang-european texlive-lang-norwegian
  - rvm get stable --auto-dotfiles
  - rvm install 2.3.3
  - gem install html-proofer
  - tlmgr install xcolor sectsty babel babel-norsk framed

script:
  - ./_build.sh
  - htmlproofer --alt-ignore images/logo.svg ./docs 

deploy:
  provider: pages                         # Specify the gh-pages deployment method
  skip_cleanup: true                      # Don't remove files
  github_token: $GITHUB_TOKEN             # Set in travis-ci.org dashboard
  local_dir: docs                         # Deploy the docs folder
  on:
    branch: master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # Speed up the html-proofer

notifications:
  email: false

